[package]
name = "typeshare"
version = "0.1.0"
authors = ["R.J. Freund <robert.joseph.freund@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"